apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bitnami-charts.yaml
- ingress-nginx-charts.yaml
- jetstack-charts.yaml
- k8s-at-home-charts.yaml
- kubernetes-dashboard.yaml
- pihole.yaml
- linkerd.yaml
- longhorn.yaml
- prometheus-community-charts.yaml
- grafana-charts.yaml
- stakater-charts.yaml
